name: Deploy to Vercel

on:
  push:
    branches:
      - main # Deploy on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 # Check out the repository code

    - name: Set up Python
      uses: actions/setup-python@v4 # Set up Python environment
      with:
        python-version: '3.12' # Specify Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run model training
      run: |
        python model.py

    - name: Deploy to Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: |
        npm install -g vercel
        vercel --prod
